### ISSUE TITLE
Rendering of rakudoc tables

### ISSUE THREAD

**Issue by sumanstats** [zag/js-pod6#11]
Thank you for creating https://pod6.in/ to render `pod6` to `html`. That was very much needed tool.

I was trying to render this content 

```
=head3 Rendering of rakudoc tables to html

=table
    Animal | Legs |    Eats
    =======================
    Zebra  +   4  + Cookies
    Human  +   2  +   Pizza
    Shark  +   0  +    Fish

=table
    X | O |
   ---+---+---
      | X | O
   ---+---+---
      |   | X

=table
    X   O
   ===========
        X   O
   ===========
            X
```

In the first table, the row content were all in single row. In the second and third tables, the column alignment was not clear.

<img width="907" alt="Capture1" src="https://user-images.githubusercontent.com/8075886/83259174-4839a780-a1d7-11ea-82ae-18cfde30d9b7.PNG">

I also tested the same with [Pod::To::HTML](https://github.com/Raku/Pod-To-HTML) which renders fine.
<img width="649" alt="Capture" src="https://user-images.githubusercontent.com/8075886/83259417-bc744b00-a1d7-11ea-87eb-2ac43525359b.PNG">

I think this could be improved in future releases.

**Comment by zag** [comment]
fixed and published at pod6.in
many thanks, @sumanstats!

**Comment by sumanstats** [comment]
Alignment is good now. One thing I noticed is there is no horizontal spacing for separate tables.

<img width="843" alt="Capture" src="https://user-images.githubusercontent.com/8075886/83866023-dfa67980-a746-11ea-9092-d7604ebfd091.PNG">

**Comment by zag** [comment]
@sumanstats, please, check now https://pod6.in
added extra space.
thank you!
![image](https://user-images.githubusercontent.com/31441/83867266-d2cb5b00-a731-11ea-9a17-0565a43d5b1c.png)

**Comment by sumanstats** [comment]
Great. Much better now.

In this table the header row is not within table border. I think it would be appropriate to put **header row** also inside the border.

<img width="857" alt="Capture" src="https://user-images.githubusercontent.com/8075886/83871909-affc6f00-a750-11ea-9e39-d4f3db6610ac.PNG">

**Comment by zag** [comment]
fix it
thank you!
