### ISSUE TITLE
Please confirm license (MIT?)

### ISSUE THREAD

**Issue by cxw42** [zag/js-pod6#19]
Thank you for writing this tool, which looks very useful!  What is the license?  The only reference I can find is "MIT", in package.json.  Is that <https://spdx.org/licenses/MIT.html>?  Thanks in advance for your response!

**Comment by zag** [comment]
hi , @cxw42 
yep, MIT.
added LICENSE file
thank you!

**Comment by cxw42** [comment]
Thanks for the quick response!
