### ISSUE TITLE
TypeError: [].concat(...).flat is not a function

### ISSUE THREAD

**Issue by raiph** [zag/js-pod6#7]
### Summary

I tried pod6.in. It didn't work. Details follow.

### My system details

I'm using:
Firefox
Version 	61.0.1
Build ID 	20180712135629
User Agent 	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0
OS 	Linux 4.15.0-29-generic
Multiprocess Windows 	1/1 (Enabled by default)
Web Content Processes 	4/4
Enterprise Policies 	Inactive
Google Key 	Found
Mozilla Location Service Key 	Missing
Safe Mode 	false

### What happened

When I arrived at pod6.in I saw a page with a title at the top (`pod6 to html (0.0.17`) and two panes.

On the left was pod:
=head1 Title
=head2 Subtitle
etc

On the right was:

There may have been an error. Check pod6 syntax at Synopsis 26 or please, fill issue here.

Technical details (please, attach this to issue):

TypeError: [].concat(...).flat is not a function

**Comment by hankache** [comment]
On Windows 10:
* Firefox 75.0: Works
* Google Chrome 80.0.3987.163: Works
* Microsoft Edge: Doesn't work. The error message is:
```
There may have been an error. Check pod6 syntax at Synopsis 26 or please, fill issue here.
Technical details (please, attach this to issue):
TypeError: Object doesn't support property or method 'flat'
```

**Comment by zag** [comment]
@raiph, @hankache  thank's for this issue!
fixed and checked under:
```
windows 10,
Microsoft EdgeHTML 17.17134
```
update will be available at https://pod6.in  as soon as possible ( check version: 0.0.18 in title )
